### ISSUE TITLE
Fix post-build issues

### ISSUE THREAD

**Issue by babak-feiz** [ibikecph/ibikecph-ios#21]
After the initial build, there are a number of minor issues with the app's basic functions. E.g. wrong text on the report buttons.

**Comment by emiltin** [comment]
this issue needs a better description. what issues are we  talking about? can this issue be closed?

**Comment by babak-feiz** [comment]
True, sorry, 

It was meant for minor issues that we experienced after successful build. E.g. wrong text on the report buttons. 

This "issue" entry is now fixed and can be closed. 

There are though still two major issues at the moment: Facebook login and routing via public transport. I'll create individual issues for those two.

**Comment by emiltin** [comment]
ok

**Comment by emiltin** [comment]
there's already an issue about facebook login: #25.
