### ISSUE TITLE
Cannot provide route suggestions using public transportation

### ISSUE THREAD

**Issue by babak-feiz** [ibikecph/ibikecph-ios#27]
When tapping on the option to route using public transportation, the app keeps saying "no route found". 

The issue can be seen in both I Bike CPH and CykelPlannen.

**Comment by emiltin** [comment]
what url is the app calling?

**Comment by emiltin** [comment]
api endpoint was disabled, has been fixed

**Comment by emiltin** [comment]
done

**Comment by babak-feiz** [comment]
Works after the fix to backend
